# TODO:
#  - Have this workflow kick off daily and update the synonyms ONLY if Anime Offline Database has been updated since last run
#
on:
  schedule:
  # Every Monday at 2:30 AM UTC
  - cron: '30 2  * * 1'
  workflow_dispatch: # Add's option to manually run workflow

jobs:
  generate-synonyms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          path: filebot-public
          fetch-depth: 0
      - name: Install Filebot # A name for your step to display on GitHub. Can include spaces
        id: step1 # A unique identifier for the step. You can use the id to reference the step in contexts. Can not include spaces
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/fbot && cd $GITHUB_WORKSPACE/fbot
          sh -xu <<< "$(curl -fsSL https://raw.githubusercontent.com/filebot/plugins/master/installer/tar.sh)"
      - name: generate-synonyms
        id: step2
        shell: bash
        run: |
          #filebot -script $GITHUB_WORKSPACE/filebot-public/scripts/generate_anidb_synonyms_from_aod.groovy --log all --def outputFolder="$GITHUB_WORKSPACE/filebot-public/datafiles"  aniDBuserAgent="${{ secrets.ANIDBUSERAGENT }}"
          MYDATE=$(date +%Y_%m_%d)
          echo "::set-output name=mydate::$(echo $MYDATE)"
      - name: Push changes
        id: step3
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ steps.step2.outputs.mydate }} - anime-synonyms"
          repository: filebot-public

