# TODO:
#  - Have this workflow kick off daily and update the synonyms ONLY if Anime Offline Database has been updated since last run
#
on:
  schedule:
  # Every Monday at 2:30 AM UTC
  - cron: '30 2  * * 1'
  workflow_dispatch: # Add's option to manually run workflow

jobs:
  generate-synonyms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          path: filebot-public
          fetch-depth: 0
      - name: Install Filebot # A name for your step to display on GitHub. Can include spaces
        id: step1 # A unique identifier for the step. You can use the id to reference the step in contexts. Can not include spaces
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/fbot && cd $GITHUB_WORKSPACE/fbot
          PACKAGE_VERSION=4.9.6
          PACKAGE_SHA256=$(curl -fsSL https://raw.githubusercontent.com/filebot/website/master/get.filebot.net/filebot/FileBot_$PACKAGE_VERSION/FileBot_$PACKAGE_VERSION-portable.tar.xz.sha256)

          PACKAGE_FILE=FileBot_$PACKAGE_VERSION-portable.tar.xz
          PACKAGE_URL=https://get.filebot.net/filebot/FileBot_$PACKAGE_VERSION/$PACKAGE_FILE

          # Download latest portable package
          curl -o "$PACKAGE_FILE" -z "$PACKAGE_FILE" "$PACKAGE_URL"

          # Check SHA-256 checksum
          echo "$PACKAGE_SHA256 *$PACKAGE_FILE" | sha256sum --check || exit 1

          # Extract *.tar.xz archive
          tar xvf "$PACKAGE_FILE"

          # Check if /path/to/filebot.sh works
          "$PWD/filebot.sh" -version

          # [OPTIONAL] Link `filebot` into the $PATH
          sudo ln -sf "$PWD/filebot.sh" /usr/local/bin/filebot

          # [OPTIONAL] Check if the `filebot` command works
          filebot -script fn:sysinfo
      - name: generate-synonyms
        id: step2
        shell: bash
        run: |
          filebot -script $GITHUB_WORKSPACE/filebot-public/scripts/generate_anidb_synonyms_from_aod.groovy --log warning --output "$GITHUB_WORKSPACE/filebot-public/datafiles"  --def aniDBuserAgent="${{ secrets.ANIDBUSERAGENT }}"
          MYDATE=$(date +%Y_%m_%d)
          echo "::set-output name=mydate::$(echo $MYDATE)"
      - name: Push changes
        id: step3
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ steps.step2.outputs.mydate }} - anime-synonyms"
          repository: filebot-public

