# TODO:
#  - Have this workflow kick off daily and update the synonyms ONLY if Anime Offline Database has been updated since last run
#
on:
  schedule:
  # Every Monday at 2:30 AM UTC
  - cron: '30 2  * * 1'
  workflow_dispatch: # Add's option to manually run workflow

jobs:
  generate-synonyms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          path: filebot-public
          fetch-depth: 0
      - name: Install Filebot
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/fbot && cd $GITHUB_WORKSPACE/fbot
          sh -xu <<< "$(curl -fsSL https://raw.githubusercontent.com/filebot/plugins/master/installer/tar.sh)"
      - name: generate-synonyms
        shell: bash
        run: |
          ls $GITHUB_WORKSPACE/filebot-public/scripts/
          ls $GITHUB_WORKSPACE/filebot-public/datafiles/
          filebot -script $GITHUB_WORKSPACE/filebot-public/scripts/generate_anidb_synonyms_from_aod.groovy --log warning --def outputFolder="$GITHUB_WORKSPACE/filebot-public/datafiles"  aniDBuserAgent="${{ secrets.ANIDBUSERAGENT }}"
      - name: Commit files
        run: |
          MYDATE=$(date +%Y_%m_%d)
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "$MYDATE - anime-synonyms" -a
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ GITHUB_TOKEN }}      

